### ISSUE TITLE
Cleave Flat Threat Modifier Not Applying

### ISSUE THREAD

**Issue by Buzzed27** [dfherr/LibThreatClassic2#21]
Cleave has values for threat, but appears to never be called.

No function for cleave appears to exist.

https://imgur.com/a/cYfXM2g

	cleave = {
		[845] = 10,
		[7369] = 40,
		[11608] = 60,
		[11609] = 70,
		[20569] = 100

**Comment by CombatLawyer** [comment]
I also noticed this, seems like it would need a 

function Warrior:Cleave(spellID)
	return threatValues.cleave[spellID] * self:threatMods()
end

and

init(self, threatValues.cleave, self.Cleave)

Unless this is accounted for somewhere outside the warrior module

**Comment by amotosouoc** [comment]
I did a test and it looks like cleave modifier is split between targets, warrior was always on **battle stance**:

1 Target test: https://classic.warcraftlogs.com/reports/tmQNap2GdkFWTcBL#fight=last
```
Cleave: 177 + 100
Rage: 3 
(177+100)*0.8+3*5 = 236.6 threat

Need 236.6*1.1 = 260.26 threat for aggro
Mage aggros at 269
```

2 Targets test: https://classic.warcraftlogs.com/reports/tmQNap2GdkFWTcBL#fight=8
```
Cleave: 395 + 100
Rage: 12
(395+100)*0.8+12*5 = 456 threat

Need 456*1.1 = 501.6 for aggro
Mage aggros at 477

If cleave modifier is shared evenly, then warrior did:
(395+50)*0.8+12*5 = 416 and mage needs 416*1.1 = 457.6 for aggro
```

**Comment by dfherr** [comment]
Easiest is probably applying half by default. Everything else would be a major rework for little gain.

**Comment by amotosouoc** [comment]
It seems I was wrong, forgot threat gained by rage is split evenly. So my previous post should look like this:
```
Cleave: 395 + 100
Rage: 12
(395+100)*0.8+12*5/2 = 426 threat

Need 426*1.1 = 468.6 for aggro
Mage aggros at 477
```
From new testings, here's another log https://classic.warcraftlogs.com/reports/XpFyLBt7nvKr6McP#fight=1

```
Threat to Felhound
Cleave: 170 + 100
Rage: 7
(170+100)*0.8 + 7*5/2 = 233.5

Need 233.5 * 1.1 = 256.85 for aggro
Mage aggros at 269
```
If I split the bonus from cleave, it doesn't work:
```
Threat to Felhound
Cleave: 170 + 50
Rage: 7
(170+50)*0.8 + 7*5/2 = 193.5

Need 193.5 * 1.1 = 212.85 for aggro
Mage aggros at 269 (doesn't rip at 255 or 236 or 213)
```
And if you don't split rage, it still doesn't work
```
(170+50)*0.8 + 7*5 = 211
Need 211 * 1.1 = 232.1 for aggro
Mage aggros at 269 (doesn't rip at 236 or 255)
```

So after all, cleave bonus isn't split between the targets. https://github.com/dfherr/LibThreatClassic2/pull/22 should be good.

To proof rage threat is split, https://classic.warcraftlogs.com/reports/rV2NQw1vA7n9RmBk#fight=4&type=summary

```
Rage: 8
8*5 = 40 threat
Need 44 for aggro
Mage aggros one mob at 22 and the other at 23

If we split the rage between the 2 mobs, we need 20*1.1 = 22 threat for aggro, which matches the results.
```
