### ISSUE TITLE
Taunt copies threat even if resisted and boss has immunity

### ISSUE THREAD

**Issue by Mard35** [dfherr/LibThreatClassic2#26]
I tried to taunt Broodlord Lashlayer at 1:50 of video, and of course it was resisted because of immunity, but addon shows, that threat was copied from player which had aggro at that moment and my threat immediatly rised from 16k to 20k. It should not be. Of course the boss did not pay attention to it, which means this copy was fake. The same shit happens on Onyxia - taunt copies threat even if resisted and addon shows fake threat.
https://youtu.be/z7DJh6LIsoI?t=109

**Comment by dfherr** [comment]
I moved the taunt handling from the spell success to the debuff application. The debuff is only applied on success as far as I could see from my logs. So this hopefully fixes  the issue.
