### ISSUE TITLE
Thunderfury threat bonus not being accounted for?

### ISSUE THREAD

**Issue by JaredR26** [dfherr/LibThreatClassic2#27]
Hi, we've had an issue where the secondary tank pulled agro off the bear main tank on Vael early, causing several deaths.  But the threatmeters did not indicate that they were close to pulling agro.  Since then we've done a few tests and we think the problem is that the thunderfury has bonus threat that is not being counted.

Test setup:
Bear using maul, with threat talent, did 50k worth of threat on a single target.
Warrior then begins to generate threat (mix of shield slam and a few abilities in the rotation).  The first trial is done with no thunderfury.  In this trial, the warrior pulls threat at almost exactly 10% over the druid's threat count.

The second trial is exactly the same but swaps the thunderfury back in.  During this trial the warrior pulled threat at 52.6k threat when the expected agro would have been just over 55k.

These threat estimate numbers are from a private server but the values would account for our test results: https://forum.elysium-project.org/topic/24166-weapon-procs-and-threat/

We did record combatlogs of both tests, as well as some other tests we did.  We can upload and/or link those if they are helpful.

Can this be fixed?

**Comment by dfherr** [comment]
We also encountered this in our raid yesterday. I was not aware thunderfury is currently not accounted for (only the damage, but not the procs). Yes, this will be fixed.

**Comment by JaredR26** [comment]
Thank you.  Let me know if there's anything I can do that would help.

**Comment by dfherr** [comment]
this should be fixed with the next version
