### ISSUE TITLE
"Improved Power word: Shield" talent info

### ISSUE THREAD

**Issue by sergeynesterov** [dfherr/LibThreatClassic2#33]
Wrong calculation of "Improved Power word: Shield" information.
Maximum talent points is 3. Not 5.

Proposed changes:
before: Priest.lua -> Priest:ScanTalents() -> "self.impPWS = 1 + (select(5, GetTalentInfo(1, 5)) * 0.05)"
after: Priest.lua -> Priest:ScanTalents() -> "self.impPWS = 1 + (select(3, GetTalentInfo(1, 5)) * 0.05)"

**Comment by dfherr** [comment]
No all is correct here. select(5,...) means to select the 5th return value of the GetTalentInfo function, which is the number of points spent in the talent. Your suggestion would select the talent texture. 😉

**Comment by sergeynesterov** [comment]
Sorry, my mistake. You are absolutely right :)
