### ISSUE TITLE
BOS threat bug - counting event when not buffed

### ISSUE THREAD

**Issue by Orvisky** [dfherr/LibThreatClassic2#35]
Hello,
we found bug that this lib count BOS even if we dont have it buffed. 
BOS got overbuffed by another paladin with PallyPower but TinyThreat and also ClassicThreatMeter2 counting still as BOS buffed and doing bad numbers in threat meters and confusion.

Attaching screenshot from BWL 12.4., Main Tank screenshot, Vaelstraz Main tank ofc didnt have BOS on him when battle starts. Sam ething happened 27.4.

When we simulated BOS in threat chart on MT http://82.130.21.56/threat/, threat numbers matched with addon data. 

![image](https://user-images.githubusercontent.com/1727586/80425553-2ac9a300-88e4-11ea-9c9d-8e5f13d4f881.png)

**Comment by Orvisky** [comment]
@dfherr can you pls tell me, in which event calcBuffMods is called? If i am assumg right, this functions is causing recalc of threat modifiers. It is possible to call it manually?

Or what happend e.g. if pala buffed me with BOS, and another pala rebuff me 1-2 sec later with BOL. BOS logically dissapers, but does this library call calcBuffMods and know that i dont have BOS?

Thank you

**Comment by Orvisky** [comment]
Or maybe is there possibility to do some command to recount buffs / print actual buffThreatMultipliers to see if everything is ok?

**Comment by dfherr** [comment]
Hi,

thanks for reporting this issue. This is already known and already fixed. See here: https://github.com/dfherr/LibThreatClassic2/issues/8#issuecomment-617000578

I will release the fix with the next revision soon.

**Comment by Orvisky** [comment]
@dfherr can you maybe also add feature to be able to get value of buffThreatMultipliers and debuffThreatMultipliers from outside? To make it available e.g. in ClassicThreatMeter2 or TinyThreat. Thank you. To be sure what value we have and maybe make it viisble on screen in frame.
