### ISSUE TITLE
Removing Blessings of Salvation doesnt always affects threat

### ISSUE THREAD

**Issue by Ainyru** [dfherr/LibThreatClassic2#36]
When tanks (or others) remove Blessings of Salvation by right clicking or macro, or when paladin who owns Blessings of Salvation replace it with other bless, library keeps calculating threat like salvation is still present. Untill combat end, when full recalculation happens, seems.

This happens becouse SPELL_AURA_REMOVED message dosnt always send correct SpellId, and it always send 0 for both blessings of salvations. Thats why addon misses fact of these blessings dissapearing.

This can be solved by catching name of removed buf (which seems always present) and transform it into spellId.

Here is how i tryed to fix this bug for my guild: https://cdn.discordapp.com/attachments/614989515291099148/705372312592973874/A_ThreatFix.zip

I hope this link will work for you. Look into "ThreatClassModuleCore.lua" file.

**Comment by dfherr** [comment]
Hi,

this has already been fixed and will be released soon with the next version. As soon as I have time.

See this issue: https://github.com/dfherr/LibThreatClassic2/issues/8

As a side note: Your solution does not work and is what the lib does anyway. Transforming the name to the spellid only works if you have the spell in your spellbook OR actively present as a buff. If the buff is removed and you are not a paladin, it's neither in your spellbook not in your buffs, so the reversal fails.

I rather just update all the auras on the UNIT_AURA event now, which even works for totems (totems don't even trigger SPELL_AURA combat log entries).

**Comment by Ainyru** [comment]
Hmm... i tested my solution as druid with pala in my group and it worked for me. Dunno what i missed.

**Comment by Ainyru** [comment]
Maybe i miss something, but im not tranfrorming name into spellid, im doing opposite: tranforming spellids into names (during addon initialization), saving this info and then using it in SPELL_AURA_REMOVED events.

This seems worked for my druid.

**Comment by dfherr** [comment]
ah yes. you can cache the names. that works, unless you reloadui with the buff present. then it doesn't work again.

**Comment by Dyaxler** [comment]
@Ainyru Which addon are you using that is using the LibThreatClassic2 library? All the major ones like Details and ThreatClassic2 are still using Rev11 which doesn't have dfherr's fixes.

You can manually download the latest LibThreatClassic2.zip and patch your addon manually until dfherr has the time to officially release his new version. I've done it myself and provided the patched addons to my guild. We've been using it for about a week and it works beautifully.

Once dfherr releases Rev12 it will still take time for the authors of the other addons to "suck in" the new revision and push it out.

**Comment by dfherr** [comment]
@Dyaxler considering I am also the author of ThreatClassic2 it takes no additional time from the Lib release to the addon release. However, I haven't released yet, because there is still a bug in the lib or tc2 (not sure yet) i'm actively working on that I wanna push out along side.

**Comment by Dyaxler** [comment]
@dfherr oh duuuuu... haha. Sorry didn't notice. I prefer it and using Recount vs using Details. I like having a second window showing my threat. ThreatClassic2 is clean and simple. Well done sir...
