### ISSUE TITLE
Huge threat difference between static analyser and LibThreatClassic2

### ISSUE THREAD

**Issue by Gymble** [dfherr/LibThreatClassic2#38]
Hi,

When analyzing computed threat variation between:
- http://82.130.21.56/threat/
- https://www.classicthreat.com
- The threat value reported by ThreatClassic2 recorded on a BWL run video (see provided screenshoot taken some seconds before the boss die as the recorder dyed from the bomb) The tank is "Enden":
![unknown](https://user-images.githubusercontent.com/64792994/80983558-f5194280-8e2c-11ea-97fb-ae75a5817c7b.png)

Note that according to this screenshoot Enden should have lost Agro. He does not.

On the following log:
https://classic.warcraftlogs.com/reports/4Wr78kgCQNcVdhLR#fight=4&type=summary

We got for our tank "Enden":
- 55k threat on http://82.130.21.56/threat/ when the recorder (oomsoon) dyed from the bomb.
- 59k threat at the end of the fight on https://www.classicthreat.com
- 37k threat reported by LibThreatClassic2.

As you can see there quite a huge difference between the two static analyses and LibThreatClassic2.
It seems that there is around a 18k threat variation on the same timepoint.
Note that the threat values of both Genese and Aeranda are quite close in LibThreatClassic2 and http://82.130.21.56/threat.

Enden is using a Thunderfury and AFAIK he is playing on a French wow client.

Thanks.

**Comment by dfherr** [comment]
I released a new version on 1st of May https://github.com/dfherr/LibThreatClassic2/releases

it fixes a bug that incorrectly applies salvation when it was removed or overbuffed until a fight ended. (i.e. if you got it buffed and then overbuffed pre fight you incorrectly had 30% less threat until the fight ended and buff mods were recalculated).

Also it fixes a bug that totem of tranquility was not recognized (because it doesn't appear in the combatlog, but I found a work around).

Finally, you can find thunder fury 145 threat here https://github.com/dfherr/LibThreatClassic2/blob/master/ThreatClassModuleCore.lua#L329-L335

Please try with the newest version (on all relevant players, tc2 has a version check built in) and report again if the issue persists.

**Comment by Gymble** [comment]
Hi dfherr, 

Thanks for the quick reply. I did inform our raid of this salvation issue and will keep you updated on this point.

Dividing the 37k threat reported on the screenshoot by 0.7 gives a threat value of almost 53k, much more in line with the static analysers (55k on this timepoint).

Regarding the Thunderfury proc, my understanding of the comments you put in the code is that both the speed debuff (90 threat) and the nature resist debuff (145 threat) are applied on the same timestamp. Thoses two debuff are applied on the main target and only the nature resist debuff is spread.
As a result, my understanding of this line of code:
`if(thunderfury.lastMobGUID ~= target or thunderfury.lastHitTimestamp + 0.01 < timestamp) then`
Is that it will never be true for the "main" target as "x+epsilon<x" will always be false.
And thus, the 145 threat of the nature resist debuff will never be added to the target that took both debuff. Unless I did miss something AFAIK this is wrong or at least justify a code review.

As a matter of fact, Enden did get 6 procs of TF on this fight. Add 145x1.3x1.15=1300 threat to the 53k we previously computed and we are now consistent with the 55k reported by 82.130.21.56

Hope this help.

Gymble.

**Comment by dfherr** [comment]
This is how a thunderfury proc looks like:
```
4/21 19:43:14.257  SPELL_AURA_APPLIED,21992,"Thunderfury",DEBUFF
4/21 19:43:14.257  SPELL_DAMAGE,21992,"Thunderfury"
4/21 19:43:14.257  SPELL_AURA_APPLIED,27648,"Thunderfury",DEBUFF
```

what this piece of code does is log 145 threat on the first `SPELL_AURA_APPLIED`, which is the slow debuff for main target, but the nature resist debuff on aoe (impossible to differentiate in-time, as spell ids are not available ingame and they have the same name). So the first debuff you apply makes 145 threat. Then the `SPELL_DAMAGE` event applies 90 bonus threat and sets a timer to ignore every `SPELL_AURA_APPLIED` event that happens in the 10ms after it.

The difference might very well be chat delay (remember other players have to send their threat data to you over the network) or other inaccuracies. ~E.g. classicthreat seems to apply bonus threat on the spell_cast event. However, the event also triggers if a skill misses/dodges/parries and thus calculates the threat incorrectly. (Enden had 7 misses on HS that makes 145 * 1,3 * 1,15 = 1517 threat too much. Sunder Armor misses are harder to see in wcl, but add even more)~ (seems to be correct afterall)

**Comment by Gymble** [comment]
Ok so first aura goes in, apply 145 to main target then spell damage add 90 and set states in order to ignore the next aura on the same target. Ok make sense. 

Thank you for your time and the explanations.

Gymble

**Comment by Gymble** [comment]
We did not see any strange result anymore since we installed the 1st may version.
Thanks a lot.
G.
