### ISSUE TITLE
Druid bear form threat modifier incorrectly calculated

### ISSUE THREAD

**Issue by Isabello** [dfherr/LibThreatClassic2#4]
Druid bear form is currently implemented as multiplicative like warrior. This is the line/file in question:

https://github.com/dfherr/LibThreatClassic2/blob/master/ClassModules/Classic/Druid.lua#L119

According to testing by AutumnRain#7088 from the FC discord, it should be additive.
```
472 crit needed 555 damage to pull
472 crit on feral druid with salv fwiw, so 472*1.1*1.45*0.7=527 or 472*1.1*1.495*0.7=543 to pull threat.
Accounting for the 5 rage from the druid critting as well we need to add in 5*5*1.1*1.45*0.7=27.9 OR 5*5*1.1*1.495*0.7=~28.8 to either one,
so with 1.45 mod we would expect 527+27= 555 to pull, if it was 1.495 we would expect 543+28.8=~572 to pull
```

**Comment by dfherr** [comment]
According to the original 1.12 patch notes (archived here http://web.archive.org/web/20101107215554/http://www.worldofwarcraft.com/patchnotes/patch1p12.html) all threat **reduction** abilites are multiplicative now. We assume that this also means threat addition abilites are multiplicative. Can someone do another test to confirm these findings?

If this is actually additive, does that also mean that Defiance for warriors is additive?

**Comment by Isabello** [comment]
I will ask for more testing to be performed. However, those patch notes indicate that the additive -> multiplicative is related to threat reduction.

Regarding warriors, I believe the testing has been very clear that it is multiplicative. The actual case could be that blizzard has incorrectly implemented Feral Instincts in Classic.

**Comment by dfherr** [comment]
The TBC addon Threat-2.0 on which this implementation is built upon actually implemented Feral instincts additive and not multiplicative, so maybe it's actually a long known "design flaw".

**Comment by dfherr** [comment]
will be fixed with the next revision.
