### ISSUE TITLE
Is this working with the New Blizzard Hotfix in classic?

### ISSUE THREAD

**Issue by bjhinkel** [dfherr/LibThreatClassic2#40]
I understand detail tiny threat was not working on the PTR Monday? Is LibThreatClassic2 going to work with the new threat api Blizzard has enabled in Classic?

**Comment by dfherr** [comment]
I think you're confusing a few things.

There was a hotfix today in the live servers for combat log range, which was originally planned for the patch 1.13.5.

On the PTR the new threat api was enabled (not a hotfix, regular patch). This library (LibThreatClassic2), which is used by tiny threat and also my addon  ThreatClassic2 https://www.curseforge.com/wow/addons/ThreatClassic2 will become obsolete.

My addon ThreatClassic2 is already prepared for that change and the current version 2.20 works live and on PTR (it automatically detects if the API is available or not). I do not know about the update plans for details, but I did inform the author of the upcoming changes he has to make. So I suspect he will release a new Details shortly before or after the patch hits live. You should not expect your live addons to work on the PTR.
